name: Variables
on: push
jobs:
  envprint:
    runs-on: ubuntu-latest
    env:
      USERNAME: ${{ vars.USERNAME }}
    steps:
      - run: echo "${BRANCH}"
      - uses: actions/checkout@v4
        with:
          ref: ${USERNAME}
      